import Mansonry, { ResponsiveMasonry } from "react-responsive-masonry"
import CollagePhoto from "../components/CollagePhoto";

export default function Collage() {
    const sources =
        [
            { source: './photos/1.webp' },
            { source: './photos/2.webp' },
            { source: './photos/3.webp' },
            { source: './photos/4.webp' },
            { source: './photos/5.webp' },
            { source: './photos/6.webp' },
            { source: './photos/7.webp' },
            { source: './photos/8.webp' },
            { source: './photos/9.webp' },
            { source: './photos/10.webp' },
            { source: './photos/11.webp' },
            { source: './photos/12.webp' },
            { source: './photos/13.webp' },
            { source: './photos/14.webp' },
            { source: './photos/15.webp' },
            { source: './photos/16.webp' },
            { source: './photos/17.webp' },
            { source: './photos/18.webp' },
            { source: './photos/19.webp' },
            { source: './photos/20.webp' },
            { source: './photos/21.webp' },
            { source: './photos/22.webp' },
            { source: './photos/23.webp' },
            { source: './photos/24.webp' },
            { source: './photos/25.webp' },
            { source: './photos/26.png' },
            { source: './photos/27.webp' },
            { source: './photos/28.webp' },
            { source: './photos/29.webp' },
            { source: './photos/30.webp' },
            { source: './photos/31.PNG' },
            { source: './photos/32.webp' },
            { source: './photos/33.webp' },
            { source: './photos/34.webp' },
            { source: './photos/35.webp' },
            { source: './photos/36.webp' },
            { source: './photos/37.webp' },
            { source: './photos/38.webp' },
            { source: './photos/39.jpg' },
            { source: './photos/40.webp' },
            { source: './photos/41.webp' },
            { source: './photos/42.webp' },
            { source: './photos/43.webp' },
            { source: './photos/44.webp' },
            { source: './photos/45.webp' },
            { source: './photos/46.jpg' },
            { source: './photos/47.webp' },
            { source: './photos/48.PNG' },
            { source: './photos/49.MOV' },
            { source: './photos/50.MP4' },
            { source: './photos/51.webp' },
            { source: './photos/52.webp' },
            { source: './photos/53.webp' },
            { source: './photos/54.webp' },
            { source: './photos/55.webp' },
            { source: './photos/56.webp' },
            { source: './photos/57.webp' },
            { source: './photos/58.webp' },
            { source: './photos/59.MOV' },
            { source: './photos/60.webp' },
            { source: './photos/61.webp' },
            { source: './photos/62.webp' },
            { source: './photos/63.webp' },
            { source: './photos/64.webp' },
            { source: './photos/65.webp' },
            { source: './photos/66.webp' },
            { source: './photos/67.webp' },
            { source: './photos/68.webp' },
            { source: './photos/69.webp' },
            { source: './photos/70.webp' },
            { source: './photos/71.webp' },
            { source: './photos/72.webp' },
            { source: './photos/73.webp' },
            { source: './photos/75.webp' },
            { source: './photos/76.webp' },
            { source: './photos/77.webp' },
            { source: './photos/78.webp' },
            { source: './photos/79.MP4' },
            { source: './photos/80.webp' },
            { source: './photos/81.webp' },
            { source: './photos/82.webp' },
            { source: './photos/83.webp' },
            { source: './photos/84.jpg' },
            { source: './photos/85.webp' },
            { source: './photos/86.webp' },
            { source: './photos/87.MOV' },
            { source: './photos/88.webp' },
            { source: './photos/89.webp' },
            { source: './photos/90.webp' },
            { source: './photos/91.webp' },
            { source: './photos/92.webp' },
            { source: './photos/93.webp' },
            { source: './photos/94.webp' },
            { source: './photos/95.webp' },
            { source: './photos/96.webp' },
            { source: './photos/97.webp' },
            { source: './photos/98.webp' },
            { source: './photos/99.webp' },
            { source: './photos/100.MP4' },
            { source: './photos/101.webp' },
            { source: './photos/102.webp' },
            { source: './photos/103.webp' },
            { source: './photos/105.webp' },
            { source: './photos/106.webp' },
            { source: './photos/107.webp' },
            { source: './photos/108.webp' },
            { source: './photos/109.webp' },
            { source: './photos/110.webp' },
            { source: './photos/111.webp' },
            { source: './photos/112.webp' },
            { source: './photos/113.webp' },
            { source: './photos/114.MP4' },
            { source: './photos/115.webp' },
            { source: './photos/116.webp' },
            { source: './photos/117.webp' },
            { source: './photos/118.MP4' },
            { source: './photos/119.webp' },
            { source: './photos/120.webp' },
            { source: './photos/121.jpg' },
            { source: './photos/122.png' }
        ]


    return (
        <section className="w-full p-6 ">
            <div className="z-10 max-w-7xl md:p-6 m-auto">
                <h1 className=" text-3xl md:text-7xl py-2">Us</h1>
                <ResponsiveMasonry columnsCountBreakPoints={{350: 3, 750: 7}}>
                    <Mansonry columnsCount={7} gutter="6px">
                        {sources.map((source, index) => (
                            <CollagePhoto key={index} source={source} />
                        ))}
                    </Mansonry>
                </ResponsiveMasonry>

            </div>
        </section>
    );
}