import React, { useState } from 'react';

const ValentineLetter = () => {
  const [isOpen, setIsOpen] = useState(false);
    const [visibleWords, setVisibleWords] = useState([]);
      const [visibleSlots, setVisibleSlots] = useState({ s1: false, s2: false, s3: false, s4: false, s5: false });

        const fullText = "Mi niña, desde el primer momento en que te conocí, todo cambió. Te convertiste en la persona que más anhelo ver, la que hace que cualquier mal día se convierta en uno bueno y que los buenos sean inolvidables. Ha pasado tanto en tan poco tiempo, tantos sentimientos, tantos recuerdos juntos, y cada uno de ellos es un tesoro que conservo en mi corazón. Tú no eres solo mi pareja Katy, tú eres mi mejor amiga, mi más grande aventura, y mi hogar. No puedo esperar a ver qué nos depara el futuro, pero mientras tú estés a mi lado, sé que será maravilloso. Así que, solo hay una cosa que necesito preguntarte... ¿Quieres ser mi San Valentín?";
          
            const words = fullText.split(" ");
              const checkpoints = [
                  Math.floor(words.length * 0.2),
                      Math.floor(words.length * 0.5),
                          Math.floor(words.length * 0.8)
                            ];

                              const handleOpen = () => {
                                  if (isOpen) return;
                                      setIsOpen(true);

                                          // Initial Delay for envelope animation
                                              setTimeout(() => {
                                                    setVisibleSlots(prev => ({ ...prev, s1: true }));
                                                          
                                                                words.forEach((_, index) => {
                                                                        setTimeout(() => {
                                                                                  setVisibleWords(prev => [...prev, index]);

                                                                                            // Trigger image slots based on word checkpoints
                                                                                                      if (index === checkpoints[0]) setVisibleSlots(prev => ({ ...prev, s2: true }));
                                                                                                                if (index === checkpoints[1]) setVisibleSlots(prev => ({ ...prev, s3: true }));
                                                                                                                          if (index === checkpoints[2]) setVisibleSlots(prev => ({ ...prev, s4: true }));
                                                                                                                                    
                                                                                                                                              // Final slot
                                                                                                                                                        if (index === words.length - 1) {
                                                                                                                                                                    setTimeout(() => setVisibleSlots(prev => ({ ...prev, s5: true })), 500);
                                                                                                                                                                              }
                                                                                                                                                                                      }, index * 80);
                                                                                                                                                                                            });
                                                                                                                                                                                                }, 2500);
                                                                                                                                                                                                  };

                                                                                                                                                                                                    return (
                                                                                                                                                                                                          <div 
                                                                                                                                                                                                                  className={`envelope-container ${isOpen ? 'open' : ''}`} 
                                                                                                                                                                                                                          onClick={handleOpen}
                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                        <div className="flap"></div>
                                                                                                                                                                                                                                                <div className="heart-seal">
                                                                                                                                                                                                                                                          <div className="white-heart"></div>
                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                          <div className="envelope"></div>
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                          <div className="letter">
                                                                                                                                                                                                                                                                                                    <div className={`media-slot slot-1 ${visibleSlots.s1 ? 'visible' : ''}`}>
                                                                                                                                                                                                                                                                                                                <img src="./valentine/1.jpeg" alt="Memory 1" />
                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                    <div className="message-text">
                                                                                                                                                                                                                                                                                                                                                {words.map((word, index) => (
                                                                                                                                                                                                                                                                                                                                                              <React.Fragment key={index}>
                                                                                                                                                                                                                                                                                                                                                                              {/* Insert dynamic image slots at checkpoints */}
                                                                                                                                                                                                                                                                                                                                                                                              {index === checkpoints[0] && (
                                                                                                                                                                                                                                                                                                                                                                                                                <div className={`media-slot slot-2 ${visibleSlots.s2 ? 'visible' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src="./valentine/3.jpeg" alt="Memory 2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {index === checkpoints[1] && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className={`media-slot slot-3 ${visibleSlots.s3 ? 'visible' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <img src="./valentine/4.jpeg" alt="Memory 3" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {index === checkpoints[2] && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className={`media-slot slot-4 ${visibleSlots.s4 ? 'visible' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src="./valentine/5.jpeg" alt="Memory 4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className={`word ${visibleWords.includes(index) ? 'visible' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {word}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </React.Fragment>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className={`media-slot slot-5 ${visibleSlots.s5 ? 'visible' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img src="./valentine/2.jpeg" alt="Final" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default ValentineLetter;